### ISSUE TITLE
Bither android app eat a lot of data!

### ISSUE THREAD

**Issue by zhuqicn** [bither/bither-android#17]
That is crazy!
![bither](https://cloud.githubusercontent.com/assets/6313395/13537935/7b44d3ec-e1fc-11e5-8fcf-c09be96001d8.jpg)

**Comment by zhuqicn** [comment]
Looks no one cares. Will uninstall today

**Comment by bithernet** [comment]
Because Bither is a decentralized SPV wallet, it has to sync with the Bitcoin network, so it will cost some data usage.
If your data usage is limited, you can set to "Sync over wifi only".

We will try to improve this in future release.

Thanks, :)
