### ISSUE TITLE
Importing old key

### ISSUE THREAD

**Issue by chrismarquardt** [bither/bither-android#18]
Hope this is the right place for this. Through a hardware defect I lost an old Bither cold wallet on an Android phone. As far as I remember it was not an HD wallet, e.g. from an older Bither version. I have the encrypted private key and the password to decrypt it. What is the best way to decrypt this key?

**Comment by chrismarquardt** [comment]
The key is not in BIP38 format, but it was saved from Bither when the cold wallet was first created. 
This is the format (it's not the actual key, but the same number of characters):

38AF00CF56FAC4A1A2E9DB216EDA2B90870DB6586AEA42B360407D81596A527984A76AE092D8BE27F03E58048E799BBD:34EF06A8C6C2B44819B20AB28991CB3B:3DBA2EEE635EA101

Again, I have the encryption password, but I can't seem to import this into Bither.

**Comment by chrismarquardt** [comment]
Okay, thanks to someone on Reddit having an idea, we solved the problem. You can close this issue.

Solution: convert string to QR code and then import it as a "Bither Private Key QR Code" - I would have never thought of this. Maybe change the Bither private text key import to recognize the ascii format? This has cost me almost a day of research.

**Comment by bithernet** [comment]
Sorry for the delay.
Since you have already solved this, I will close this issue.

:)
