### ISSUE TITLE
How can I monitor cold HD account?

### ISSUE THREAD

**Issue by Bitim** [bither/bither-android#19]
I didn't understand how to monitor cold HD account. I don't understand which QR I need to scan from the cold wallet to the hot.
What is the process?
Thanks.

**Comment by bithernet** [comment]
In the setting page of Cold Wallet, you can find "HD monitoring QR -Code" if you have already created a Cold HD Account.
In the setting page of Hot Wallet, you can find "Monitoring HD Account".

After monitoring, check the first address of your Cold is same as your Hot.

If everything is ok, you can try with your Hot and Cold wallets with small amount of bitcoins for offline signing.

**Comment by Bitim** [comment]
It's giving a message that I need to upgrade to version 1.6.0, although I already have version 1.6.0 installed.

**Comment by bithernet** [comment]
Is your cold wallet's version 1.6.0?

**Comment by Bitim** [comment]
Yes,

**Comment by bithernet** [comment]
You should have two devices, one for Cold, and the other one for Hot.

On your Cold phone, create a HD account.
On your Hot phone, use Monitoring Cold HD, and scan the Cold Phone's HD monitoring QR-Code.

Then everything will be ok.

Both of your Cold and Hot phone should run with Bither v1.6.0.

You can look at our manuals for more details : https://github.com/bither/bither-doc

**Comment by Bitim** [comment]
I do have cold device, and hot device. One android device and the other is iPhone. Both of them running version 1.6.0, but still I get this message that I need to upgrade to version 1.6.0 when I try to scan the cold HD monitoring QR code.

**Comment by songchenwen** [comment]
Are you scanning the right QR Code on Bither Cold? The right `HD Account Monitor QR Code` is from the QR Code icon on the Cold HD Account item.

**Comment by bithernet** [comment]
@Bitim , we have just tried the Cold HD Monitoring process, and everything is ok.

It seems that you are trying to scan the wrong QR-Code.

**Comment by Bitim** [comment]
Thanks, it's working.
