### ISSUE TITLE
Cold HD account change address

### ISSUE THREAD

**Issue by Bitim** [bither/bither-android#20]
Hi,
I wondered if when I create new unsigned transaction in hot HD account monitoring wallet, the change address is the same as the input address? Or the hot wallet creates new address for change?
As you know you need to "spend" all the bitcoin in an input address you use for transaction, even if you want to use only part of the amount in the input address. The change is send to address as part of the transaction output. Also it's not safe to use the same bitcoin address more then one time, for privacy concerns, so change should send to newly created address of you wallet.
Thanks.

**Comment by bithernet** [comment]
Hot HD wallet is used to monitoring the Cold HD account.
And it will rotate address after receive transaction. Also the change address will be rotated too.
