### ISSUE TITLE
比太钱包HD账户生成新地址的HD路径

### ISSUE THREAD

**Issue by qyvlik** [bither/bither-android#27]
之前使用 `bitcoinj` 生成 HD 账户后，可以自行指定 `HD` 路径进行生成。

例如根据 [bip-0044.mediawiki的path-levels](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#path-levels) 生成新地址，其路径是 `m / purpose' / coin_type' / account' / change / address_index` 其层级为 6（包括 m）。

那么比太钱包 HD 账户生成新地址的 HD 路径是如何规划的？层级多深？

@bithernet

**Comment by zhumingu** [comment]
比太钱包的hd是bip44标准钱包  m / purpose' / coin_type' / account' / change / address_index ，所以比太钱包的账户可以兼容其他bip44钱包账户

**Comment by XingZheZ** [comment]
好
