### ISSUE TITLE
Feature Request: Import BIP38 encrypted private key in cold wallet

### ISSUE THREAD

**Issue by dskloet** [bither/bither-android#3]
I think this would be a great use case for Bither.
Keep your cold storage encrypted on a paper wallet and when you want to spend it, import it into a cold Bither wallet. Easy to make backups and the keys never touch the internet.

**Comment by spongeeluv** [comment]
hello i will be brief.. i created a paper wallet in bitaddress.org. Bip38 is a great invention..even if someone finds your private key they cant sweep it to take the funds without the paraphrase. Now how do we change it back to a private key so we can spend the funds?..and please nobody mention bit2factor.org...they are selling the domain name...im proper depressed i have a lot of bitcoin on a  bip38 private key. I have the private key. and the paraphrase .So where do i put this information please?...and do remember all bip38 private keys start with 6p....i wrote this early through the week here goes.....hello my name is mohammed ayyub. I unfortunately have some bitcoin on a private key encrypted with bip38.  My Private key is  starting with 6P. IF YOU CAN HELP ME I WILL DONATE some bitcoin towards the cause. I also have a website (Bitgangstar.com) promoting bonafide bitcoin info etc. For your help i will give you 1NEEHJLFSdH3hggF77iaMXPAfuoVMuYA4g....(.£41.23) Please check public key in Block chain explorer or any bitcoin website you can check public key status. Status of the key is unspent. You can spend  the funds providing you have the  private key and Paraphrase. Thank you hope to hear from you soon.  I have tried the Bit2factor.org website they are no  longer  live. They are selling the domain name. ($499.00 usd )...The minute you direct me to the right place i will give you some bitcoin for your time and help


p.s(I'm too embarrassed to tell you how much bitcoin i have on  a previous bip38 encrypted private key address ) boohoo.. :(

**Comment by bithernet** [comment]
Bither supports BIP38 import

2017-12-20 8:21 GMT+08:00 spongeeluv <notifications@github.com>:
