### ISSUE TITLE
无法导出密语提示密码错误但是发送比特币时候密码是正确的

### ISSUE THREAD

**Issue by HelloThisWorld** [bither/bither-android#30]
Hi 你好
我在使用安卓版比太钱包1.6.8版本时遇到问题
当我想导出HD账户密语时提示需要输入密码，我输入了密码后一直提示密码错误，其他需要输入密码的操作如HD账户二维码，修改密码，重载交易数据等均提示密码错误，但是使用钱包发送比特币时密码正确，但是发送的交易长时间得不到确认

**Comment by bithernet** [comment]
发送的交易长时间得不到确认，则表示您付的矿工费过低了。

关于密码，请用 check private keys 功能检查下密码是否正确。
