### ISSUE TITLE
比太钱包获取BTG用冷钱包签名交易时退出！

### ISSUE THREAD

**Issue by dujbo** [bither/bither-android#33]
热钱包是ANDROID手机，冷钱包是IOS。
获取BTG时，用冷钱包签名BTG发送交易时，扫描完成后直接退出，无任何提示！
原以为需要升级冷钱包，把冷钱包里的面私钥全部作废，删除冷钱包，然后联网重新安装冷钱包，又重新逐笔导入新的私钥，他妈的折腾了一个小时。
重新在热钱包获取BTG，冷钱包扫描完交易后还是直接退出！！！
------------------------------------------------------------------------------
比太包钱包究竟在搞什么？！难道不知道用户用你的钱包很大程度上是看中冷、热存储功能吗？连一个领取BTG的功能都做不完善，还让用户怎么放心用！
而且最可气的是发送BTG地址只能发到比特派钱包地址，强迫用户使用比特派钱包，增加用户的转账成本，我看你们也是快了！反正我以后是不会用了，去你妈的！

**Comment by bithernet** [comment]
1、一对一蓝牙配对升级冷钱包，这没什么不合理的，这并不意味这私钥全部作废；
2、需要升级冷钱包才能提取 BTG，是因为 BTG 的地址格式改了，过不了冷钱包的目的地址校验，这有问题吗？
3、比太不支持 BTG，只支持提取 BTG 的功能，这是因为比太是去中心化的钱包，需要连接比特币网络上的节点，如果比太支持多种数字货币，则需要连接多种节点，这开销太大。因此才需要让你发往比特派（并且，我们不希望你误操作发往错误地址），你要是不满意，可以自己做一个别的。

另外，需要“去”的是“你妈”，回家“去你妈的”吧，骂人不会让你过的更好，自会显露你的卑劣和无知，祝幸福。

**Comment by bithernet** [comment]
另外，冷钱包不建议用 iOS，因为苹果强制要求定期联网检查应用程序的证书
