### ISSUE TITLE
获取BTG的交易，使用冷钱包签名有问题

### ISSUE THREAD

**Issue by ysy** [bither/bither-android#35]
冷钱包扫描了交易二维码以后，没有反应。

似乎是 class QRCodeTxTransport 中的 formatQRCodeTransport 没有对非BTC地址的TX做处理。 

isAddressHex 如果非BTC地址返回false

    private static boolean isAddressHex(String str) {
        System.out.println("Is Address check, " + str);
        boolean isAddress = false;
        if (str.length() % 2 == 0) {
            try {
                String address = Base58.hexToBase58WithAddress(str);
                isAddress = Utils.validBicoinAddress(address);
                System.out.println(isAddress);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

**Comment by ysy** [comment]
补充：冷热钱包都是Android 1.7.8 版本，密钥是普通私钥，不是HD的。

**Comment by lujunZhang** [comment]
升级最新版到1.8.0，这个地址校验问题之前版本已经修复
