### ISSUE TITLE
Proposal logo

### ISSUE THREAD

**Issue by gitgamer** [bither/bither-android#42]
Hey thankss for your work ..!!!

I maked a proposal for corporate image you can see here ..
https://steemit.com/utopian-io/@orelmely/proposal-logo-to-bither-a-simple-open-source-wallet-bitcoin-fully-editable
Blessings!!

**Comment by bithernet** [comment]
Wow, you are so talented.
Thanks for your amazing jobs!

**Comment by dibon-github** [comment]
Good Day, I also made a proposal about new in app logos and icon for Bither
You can check my work here:
https://utopian.io/utopian-io/@baa.steemit/proposal-for-a-new-in-app-logo-and-icon-for-bither-bitcoin-wallet
