### ISSUE TITLE
编译bither-android无法通过

### ISSUE THREAD

**Issue by Crazy-Ann** [bither/bither-android#45]
内部引用Bitherj，我将bitherj加入工程后发现缺少许多类，咱们的bitherj是不是很久没有上传代码了？

**Comment by bithernet** [comment]
当然不是，是需要 sub module

**Comment by hewking** [comment]
我也遇到这个问题，需要sub module 我没明白，请问怎么处理?

**Comment by SephirothLT** [comment]
同问@bithernet
