### ISSUE TITLE
Bither new Installed

### ISSUE THREAD

**Issue by Ulli75** [bither/bither-android#65]
Hello
I'm very new in Bitcoin and Wallets.
I installed Bither Wallet on my PC and also tranfered some money to the Wallet.
Now i have a new Computer and I installed Bither again but I cant see my old Wallet Adress neither my Money,my old Password is still Working,what to do?how can I come back to my old Wallet Adress and my Money?
thanks for help

**Comment by bithernet** [comment]
You should sync to the newest block.
You can find the block syncing status in Advanced Options-Network Monitoring-Peers/Blocks.
