### ISSUE TITLE
bither.net最新版本是1.9.8 这里tag才到1.8.2是不是不后续的不开源了

### ISSUE THREAD

**Issue by buzhidaocommon** [bither/bither-android#67]
请问有安卓的历史版本下载列表不，我想下载不同版本

**Comment by songchenwen** [comment]
每个版本都是以 Github 上的代码来打包的。只是这几个版本没打tag。你可以通过 master 分支的提交记录找到旧版的代码。

**Comment by calenking** [comment]
@songchenwen 现在IOS版本，为什么无法做冷钱包了？
