### ISSUE TITLE
Missing tag for latest release 2.0.1

### ISSUE THREAD

**Issue by emanuelb** [bither/bither-android#73]
https://play.google.com/store/apps/details?id=net.bither
Current Version
2.0.1

while latest tag/release is 2.0.0
https://github.com/bither/bither-android/tags

The commit that changed version to 2.0.1 is: https://github.com/bither/bither-android/commit/006caede197c709689c721db25d465b28ed7a8ce
There currently 2 newer commit after it in master branch, which might been used to compile the release app.

**Comment by songchenwen** [comment]
The new version is tagged
